# DB-SERVER CONFIGURATION
- name: db configuration
  hosts: db_server
  tasks:
    - name: install mariadb and PyMySQL
      become: yes
      yum:
        name: 
            - mariadb-server
            - python3-PyMySQL
        state: latest

    - name: start mariadb
      become: yes  
      command: systemctl start mariadb

    - name: enable mariadb
      become: yes
      systemd: 
        name: mariadb
        enabled: true

    - name: copy the sql script
      copy:
        src: ~/db-load-script.sql
        dest: ~/

    - name: Create password for the root user
      mysql_user:
        login_password: ''
        login_user: root
        name: root
        password: "clarus1234"

    - name: copy the .my.cnf file
      copy:
        src: ~/.my.cnf
        dest: ~/

    - name: Create db user with name 'remoteUser' and password 'clarus1234' with all database privileges
      mysql_user:
        name: kodal035
        password: "12345"
        login_user: "root"
        login_password: "clarus1234"
        priv: '*.*:ALL,GRANT'
        state: present
        host: "{{ hostvars['web_server'].ansible_host }}"

    - name: Create database schema
      mysql_db:
        name: ecomdb
        # login_user: root
        # login_password: "clarus1234"
        state: present




    - name: check if the database has the table
      shell: |
        echo "USE ecomdb; show tables like 'products'; " | mysql
      register: resultOfShowTables

    - name: DEBUG
      debug:
        var: resultOfShowTables

    - name: Import database table
      mysql_db:
        name: ecomdb   
        state: import  
        target: ~/db-load-script.sql 
      when: resultOfShowTables.stdout == "" 

    - name: restart mariadb
      become: yes
      service: 
        name: mariadb
        state: restarted








# WEB-SERVER CONFIGURATION
- name: web server configuration
  hosts: web_server
  become: yes
  tasks: 
    - name: install the latest version of Git, Apache, Php, Php-Mysqlnd
      package:
        name: 
          - git
          - httpd
          - php
          - php-mysqlnd
        state: latest

    - name: start the server and enable it
      service:
        name: httpd
        state: started
        enabled: yes

    - name: clone the repo of the website
      shell: |
        if [ -z "$(ls -al /var/www/html | grep .git)" ]; then
          git clone https://github.com/kodal035/deneme.git /var/www/html/
          echo "ok"
        else
          echo "already cloned..."
        fi
      register: result

    - name: DEBUG
      debug:
        var: result

    - name: Replace a default entry with our own
      lineinfile:
        path: /var/www/html/index.php
        regexp: '172\.20\.1\.101'
        line: "$link = mysqli_connect('{{ hostvars['db_server'].ansible_host }}', 'kodal035', '12345', 'ecomdb');"
      when: not result.stdout == "already cloned..."





    - selinux:
        state: disabled    

    - name: Restart service httpd
      service:
        name: httpd
        state: restarted